### ISSUE TITLE
Yo dawg

### ISSUE THREAD

**Issue by ccremer** [mhutter/registry-cleaner#2]
Might wanna integrate it here as a new sub command or something? https://github.com/appuio/seiso 😄

**Comment by mhutter** [comment]
No, probably not. This tool works on a very low level, interacting with the registries' backend storage directly and deleting objects there. See https://wiki.vshn.net/display/APPU/Docker+Registry+Storage
Not only do you need cluster-admin permissions on OpenShift, you also need the S3 credentials of the registry.

Most of the code in this repo will hopefully only needed to be run once, the rest should be fixed in OpenShift or the registry component.

**Comment by ccremer** [comment]
Hm, haven't thought of the credentials.
though we could mention that this feature would be explicitly for cluster admins, seiso isn't meant to be _only_ used by developers, but also in CI pipelines etc.

If you think it doesn't make sense that's fine by me :+1:

**Comment by mhutter** [comment]
👍 will send a PR for seiso if anything useful drops out of this research
